cacheFolder: .yarn/cache

changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
